
# generated by: jx gitops variables
export APP_NAME="octant-jx"
export BRANCH_NAME="master"
export BUILD_NUMBER="1"
export DOCKERFILE_PATH="Dockerfile"
export DOCKER_REGISTRY="gcr.io"
export DOCKER_REGISTRY_ORG="jenkinsxio"
export JX_CHART_REPOSITORY="http://jenkins-x-chartmuseum:8080"
export PIPELINE_KIND="release"
export REPO_NAME="octant-jx"
export REPO_OWNER="jenkins-x"
export VERSION="1.0.1"
